version: '2'
services:
  video-yolo:
    build: .
    container_name: video-yolo
    ports:
      - "3000:3000"
    volumes:
      - ${SAVE_PATH}/resources:/home/video-yolo/resources
      - ${SAVE_PATH}/results:/home/video-yolo/results