version: "3"

services:
  slackbot:
    build: .
    container_name: video-yolo-slackbot
    command: [ "python", "./slackbot.py" ]
    volumes:
      - ${ANALYTICS_RESULT_BASE_PATH}:/home/video-yolo/results/analytics
      - ${SUPER_RESOLUTION_RESULT_BASE_PATH}:/home/video-yolo/results/super_resolution
      - ${AUDIO_SAVE_PATH}:/home/video-yolo/results/audio
      - ${VIDEO_SAVE_PATH}:/home/video-yolo/results/video

  api:
    build: .
    container_name: video-yolo-api
    command: [ "python", "./api.py" ]
    ports:
      - "3000:3000"
    volumes:
      - ${ANALYTICS_RESULT_BASE_PATH}:/home/video-yolo/results/analytics
      - ${AUDIO_SAVE_PATH}:/home/video-yolo/results/audio
      - ${VIDEO_SAVE_PATH}:/home/video-yolo/results/video