version: "3"

services:
  video-yolo:
    build: .
    container_name: video-yolo
    ports:
      - "3000:3000"
    volumes:
      - ${ANALYTICS_RESULT_BASE_PATH}:/home/video-yolo/results/analytics
      - ${AUDIO_SAVE_PATH}:/home/video-yolo/results/audio
      - ${VIDEO_SAVE_PATH}:/home/video-yolo/results/video